name: tmotif
channels:
  - conda-forge
  - defaults
dependencies:
  # Development deps
  - cmake
  - ipython
  - llvm-openmp
  - pip
  - python=3.9.*
  - boost-cpp
  - fmt
  - cudatoolkit=11.3 # comment out on osx-arm64
  - cudatoolkit-dev=11.3 # comment out on osx-arm64
  - pip:
    - pyyaml
​
  # Install the above using conda env create -f environment.yml
​
  # Post installation:
  # conda env config vars set CPATH="${CONDA_PREFIX}/include:${CPATH}"
  # conda env config vars set LD_LIBRARY_PATH="$CONDA_PREFIX/lib64:$LD_LIBRARY_PATH"
​
  # Then reactivate the environment